### ISSUE TITLE
Multispeaker training issue

### ISSUE THREAD

**Issue by kafan1986** [FENRlR/MB-iSTFT-VITS2#13]
I have multispeaker data. I am using train_ms.py script. I have few questions.

a) Do I need to update the "n_speakers" to match the number of distinct speakers in my dataset?
b) I am currently running training with "n_speakers" = 0 (default) and the training is around 60K. The generated output seems bad specially in terms of duration of generated audio vs ground truth duration. The generated output duration is 7 seconds whereas ground truth duration is 11 seconds.
c) During the training I have updated the config "max_text_len" to 320 from default 190, to allow more segments to pass the threshold as my dataset has some longer utterances/transcript. Can this be an cause for the issue for quality issue that is being noticed?

**Comment by FENRlR** [comment]
Yes, `n_speakers` should be matched with the total number of speakers you have.
I haven't tried modifying that max text length so there is nothing I can say about it.

**Comment by kafan1986** [comment]
> Yes, `n_speakers` should be matched with the total number of speakers you have. I haven't tried modifying that max text length so there is nothing I can say about it.

It is throwing this error.

`AttributeError: 'HParams' object has no attribute 'gin_channels'`

What should be the ideal value of this gin_channels? So that I can add it to config file.

**Comment by FENRlR** [comment]
You can add `"gin_channels": 256` to the model section of your configuration file.
```
{
    "model": {
      "gin_channels": 256
    }
  }
  ```

**Comment by shigabeev** [comment]
@FENRlR have you got any models successfully trained with multispeaker with this repo? 2 years ago it didn't work. Wondering if it's worth running as-is  🤔

**Comment by FENRlR** [comment]
@shigabeev I had a plan to train it with my own multispeaker dataset but was never able to finish it. For current version, I had a quick test with VCTK dataset for an epoch and saw it ran without errors.

On the performance side, unlike [the default decoder from VITS (L883)](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/035e92c5d4bfdfa9a37833b81bb12eed077558e7/models.py#L883), the istft decoders do not add speaker embedding ([L954](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/035e92c5d4bfdfa9a37833b81bb12eed077558e7/models.py#L954), [L1034](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/035e92c5d4bfdfa9a37833b81bb12eed077558e7/models.py#L1034), [L1133](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/035e92c5d4bfdfa9a37833b81bb12eed077558e7/models.py#L1133)). I kept them same as the original but then I found out the test for multispeaker was never held from the original MB-iSTFT-VITS repo. So maybe it should be added.
