### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by KevinWang676** [FENRlR/MB-iSTFT-VITS2#9]
Hi, I was using `cjke_cleaners2` to clean the texts. However, I got the error `ValueError: too many values to unpack (expected 2)` as shown below 

![image](https://github.com/FENRlR/MB-iSTFT-VITS2/assets/126712357/96bbcbc6-b0a6-4407-b968-c1ac3a5c4e92)

But I don't think I got more than 2 values to unpack. Here is the structure of my cleaned texts

![image](https://github.com/FENRlR/MB-iSTFT-VITS2/assets/126712357/e2c0f8b7-7ef1-4422-ab41-54bf726c6143)

So I wonder which step could go wrong. Thank you!

**Comment by FENRlR** [comment]
Since `self.audiopaths_and_text` comes from a simple [split](https://github.com/Bohemian-self/MB-iSTFT-VITS2/blob/main/utils.py#L138), it would be a text issue. Try finding a line that contains the letter "|" more than once.
